// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9jgHrrIYaRiv4YsfZSKkcJTsF1CgM3Ik',
    appId: '1:577627650967:web:d43c9d56ee24a63361e2d2',
    messagingSenderId: '577627650967',
    projectId: 'goride-9827a',
    authDomain: 'goride-9827a.firebaseapp.com',
    storageBucket: 'goride-9827a.firebasestorage.app',
    measurementId: 'G-148BW29X25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4k_fOuFpkz6Yw6Z8CuYbdBnaPqC5-CWw',
    appId: '1:577627650967:android:5374e6e196bf186361e2d2',
    messagingSenderId: '577627650967',
    projectId: 'goride-9827a',
    storageBucket: 'goride-9827a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQddnJMdCm6SE6-Q9RydDuQy9bfcWetXc',
    appId: '1:577627650967:ios:90d55d893be679bb61e2d2',
    messagingSenderId: '577627650967',
    projectId: 'goride-9827a',
    storageBucket: 'goride-9827a.firebasestorage.app',
    iosBundleId: 'com.rideguyana.app.testProject',
  );
}
